spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useunicode=true&characterEncoding=utf8
    username: root
    password: xiong123
mybatis:
  type-aliases-package: com.ckdl.domain
  mapper-locations: classpath:mapper/*Mapper.xml