server:
  port: 9001
spring:
  application:
    name: service_goods
  datasource:
    druid:
      min-idle: 5
      max-active: 5
      initial-size: 5
      time-between-eviction-runs-millis: 60000        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      password: xiong123
      username: root
      url: jdbc:mysql://localhost:3306/qingcheng_goods?useUnicode=true&characterEncoding=UTF-8
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
  thymeleaf:
    cache: false
  pagehelper:
    helper-dialect: mysql   #数据库连接
    reasonable: true        #分页合理化参数
#  mybatis:
#    mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
#    type-aliases-package: com.ckdl.pojo  # 注意：对应实体类的路径
